// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "bee":return img`
.........ccc........
......cccc3cc.......
.....cc3c3c3c.......
.....c33ccbcc.......
.....cb3cb3b3c......
.....ccccccc3c......
.....c33bbc33c......
.....cc333cccc......
......ccccc7..6.....
...........7666.....
.......5..766.......
.......7776.........
........76..........
........6...........
........6...........
........6...........
........66..........
.........6..........
....................
....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
